import { deepClone, toISODate } from "./utils.js";

const ISO = toISODate;

const componentMetadata = [
  {
    id: "button",
    title: "Button",
    kind: "component-story",
    description: "Pressable action trigger supporting primary and secondary variants.",
    component: "fable-button",
    storyGroup: "Button",
    createdAt: toISODate("2024-05-01"),
    updatedAt: toISODate("2024-05-01"),
    keywords: ["cta", "action"],
    taxonomy: {
      group: "Inputs",
      category: "Components",
      tags: ["button", "action"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "badge",
    title: "Badge",
    kind: "component-story",
    description: "Inline status indicator with tone-aware variants.",
    component: "fable-badge",
    storyGroup: "Badge",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["status", "label"],
    taxonomy: {
      group: "Feedback",
      category: "Components",
      tags: ["badge", "status"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "card",
    title: "Card",
    kind: "component-story",
    description: "Surface container with title + body slots for flexible content blocks.",
    component: "fable-card",
    storyGroup: "Card",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["container", "layout"],
    taxonomy: {
      group: "Layout",
      category: "Components",
      tags: ["card", "layout"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "checkbox",
    title: "Checkbox",
    kind: "component-story",
    description: "Form input representing binary selection with label.",
    component: "fable-checkbox",
    storyGroup: "Checkbox",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["form", "toggle"],
    taxonomy: {
      group: "Inputs",
      category: "Components",
      tags: ["checkbox", "form"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "code-block",
    title: "Code Block",
    kind: "component-story",
    description: "Pre-styled code snippet block with copy affordance.",
    component: "fable-code-block",
    storyGroup: "Code Block",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["documentation", "code"],
    taxonomy: {
      group: "Foundations",
      category: "Components",
      tags: ["code", "docs"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "drawer",
    title: "Drawer",
    kind: "component-story",
    description: "Anchored overlay for navigation or contextual content.",
    component: "fable-drawer",
    storyGroup: "Drawer",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["overlay", "dialog"],
    taxonomy: {
      group: "Navigation",
      category: "Components",
      tags: ["drawer", "overlay"],
      status: "alpha",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "header",
    title: "Header",
    kind: "component-story",
    description: "Top-level header providing product name and controls.",
    component: "fable-header",
    storyGroup: "Header",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["nav", "chrome"],
    taxonomy: {
      group: "Layout",
      category: "Components",
      tags: ["header", "navigation"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "icon-button",
    title: "Icon Button",
    kind: "component-story",
    description: "Circular button for contextual icon-only actions.",
    component: "fable-icon-button",
    storyGroup: "Icon Button",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["button", "icon"],
    taxonomy: {
      group: "Inputs",
      category: "Components",
      tags: ["icon", "button"],
      status: "beta",
      platforms: ["web"],
      accessibility: "enhanced",
    },
  },
  {
    id: "input",
    title: "Input",
    kind: "component-story",
    description: "Text input field with label and helper support.",
    component: "fable-input",
    storyGroup: "Input",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["form", "text"],
    taxonomy: {
      group: "Inputs",
      category: "Components",
      tags: ["input", "form"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "link",
    title: "Navigation Link",
    kind: "component-story",
    description: "Internal navigation link with active states.",
    component: "fable-link",
    storyGroup: "Link",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["nav", "link"],
    taxonomy: {
      group: "Navigation",
      category: "Components",
      tags: ["link", "navigation"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "nav-group",
    title: "Navigation Group",
    kind: "component-story",
    description: "Sidebar accordion used to organize navigation items.",
    component: "fable-nav-group",
    storyGroup: "Navigation Group",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["navigation", "accordion"],
    taxonomy: {
      group: "Navigation",
      category: "Components",
      tags: ["nav", "accordion"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "preview",
    title: "Preview Frame",
    kind: "component-story",
    description: "Container used to showcase stories with chrome controls.",
    component: "fable-preview",
    storyGroup: "Preview",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["preview", "docs"],
    taxonomy: {
      group: "Foundations",
      category: "Components",
      tags: ["preview", "docs"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "select",
    title: "Select",
    kind: "component-story",
    description: "Form select dropdown with label and helper slot.",
    component: "fable-select",
    storyGroup: "Select",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["form", "dropdown"],
    taxonomy: {
      group: "Inputs",
      category: "Components",
      tags: ["select", "form"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "sidebar",
    title: "Sidebar",
    kind: "component-story",
    description: "Navigation sidebar shell component for story explorer.",
    component: "fable-sidebar",
    storyGroup: "Sidebar",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["layout", "navigation"],
    taxonomy: {
      group: "Layout",
      category: "Components",
      tags: ["sidebar", "navigation"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "stack",
    title: "Stack",
    kind: "component-story",
    description: "Layout helper arranging children vertically with gaps.",
    component: "fable-stack",
    storyGroup: "Stack",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["layout", "stack"],
    taxonomy: {
      group: "Layout",
      category: "Components",
      tags: ["stack", "layout"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
  {
    id: "textarea",
    title: "Textarea",
    kind: "component-story",
    description: "Multi-line text input with label and helper.",
    component: "fable-textarea",
    storyGroup: "Textarea",
    createdAt: ISO("2024-05-01"),
    updatedAt: ISO("2024-05-01"),
    keywords: ["form", "text"],
    taxonomy: {
      group: "Inputs",
      category: "Components",
      tags: ["textarea", "form"],
      status: "beta",
      platforms: ["web"],
      accessibility: "baseline",
    },
  },
];

const componentMetaMap = new Map(componentMetadata.map((meta) => [meta.id, meta]));

export const listComponentMetadata = () => componentMetadata.map(deepClone);

export function getComponentStoryMeta(id, overrides = {}) {
  const base = componentMetaMap.get(id);
  if (!base) {
    throw new Error(`Component metadata not found for id "${id}"`);
  }
  return { ...deepClone(base), ...overrides };
}

export function getComponentMetadataByComponent(tagName) {
  for (const meta of componentMetadata) {
    if (meta.component === tagName) {
      return deepClone(meta);
    }
  }
  return null;
}

export default componentMetadata;
